data_path: 'streams/BPIC2012_W/event_stream.csv'

process_fitness_threshold: 0.5
process_error_threshold: 0.9
arrival_error_threshold: 60
res_error_threshold: 0.5
wt_error_threshold: 240
et_error_threshold: 180
                  