data_path: 'streams/BPIC2017_W/event_stream.csv'

process_fitness_threshold: 0.7
process_error_threshold: 0.9
arrival_error_threshold: 300
res_error_threshold: 0.7
wt_error_threshold: 180
et_error_threshold: 300
                  