data_path: 'streams/Production/event_stream.csv'

process_fitness_threshold: 0.9
process_error_threshold: 0.9
arrival_error_threshold: 120
res_error_threshold: 0.7
wt_error_threshold: 240
et_error_threshold: 300
                  